project:
  type: website
  output-dir: docs

website:
  title: "Iago Mamede"
  navbar:
    title: "Iago Mamede"
    logo: assets/img/stochastic-icon.png
    logo-alt: "Stochastic thermodynamics icon"
    left:
      - text: "Home"
        href: index.qmd
      - text: "Research"
        href: projects.qmd
      - text: "Publications"
        href: publications.qmd
      - text: "CV"
        href: cv.qmd
      - text: "Contact"
        href: contact.qmd
    right:
      - icon: github
        href: https://github.com/iagomamede
      - text: "Google Scholar"
        href: "https://scholar.google.com/citations?user=IzlSrFEAAAAJ&hl=en"

  page-footer:
    left: "Iago Mamede"
    right: "Stochastic thermodynamics and nonequilibrium statistical physics"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    page-layout: full
    smooth-scroll: false
