project:
  type: website
  output-dir: docs

website:
  title: ""
  navbar:
    title: ""
    left:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
      - text: "Research"
        href: research.qmd
      - text: "Notes"
        href: notes.qmd
      - text: "Projects"
        href: projects.qmd
      - text: "Publications"
        href: publications.qmd
      - text: "CV"
        href: cv.qmd
      - text: "Contact"
        href: contact.qmd
    right:
      - icon: github
        href: https://github.com/iagomamede
      - text: "Google Scholar"
        href: "https://scholar.google.com/citations?user=IzlSrFEAAAAJ&hl=en"

  # page-footer:
  #   left: "Iago Mamede"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    page-layout: full
    smooth-scroll: false
